### ISSUE TITLE
Plugin exception on IDE start

### ISSUE THREAD

**Issue by VVVHawk** [dprint/dprint-intellij#95]
Hey there,

every time I open my IDE the plugin throws two equal errors:
```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 14 column 6 path $.typescript.exportDeclaration.forceMultiLine
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
	at com.google.gson.internal.Streams.parse(Streams.java:58)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:146)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:110)
	at com.dprint.utils.FileUtilsKt.checkIsValidJson(FileUtils.kt:118)
	at com.dprint.utils.FileUtilsKt.validateConfigFile(FileUtils.kt:40)
	at com.dprint.utils.FileUtilsKt.getValidConfigPath(FileUtils.kt:51)
	at com.dprint.services.editorservice.EditorServiceManager.initialiseFreshEditorService(EditorServiceManager.kt:195)
	at com.dprint.services.editorservice.EditorServiceManager.restartEditorService$lambda$5(EditorServiceManager.kt:247)
	at com.dprint.services.editorservice.EditorServiceTaskQueue$createTaskWithTimeout$task$1.run$lambda$0(EditorServiceTaskQueue.kt:64)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 14 column 6 path $.typescript.exportDeclaration.forceMultiLine
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1754)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:588)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:498)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:875)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:820)
	at com.google.gson.internal.Streams.parse(Streams.java:46)
	... 15 more
```
and then the same error with an initialized editor service:
```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 14 column 6 path $.typescript.exportDeclaration.forceMultiLine
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
	at com.google.gson.internal.Streams.parse(Streams.java:58)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:146)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:110)
	at com.dprint.utils.FileUtilsKt.checkIsValidJson(FileUtils.kt:118)
	at com.dprint.utils.FileUtilsKt.validateConfigFile(FileUtils.kt:40)
	at com.dprint.utils.FileUtilsKt.getValidConfigPath(FileUtils.kt:51)
	at com.dprint.services.editorservice.process.EditorProcess.initialize(EditorProcess.kt:32)
	at com.dprint.services.editorservice.v5.EditorServiceV5Impl.initialiseEditorService(EditorServiceV5.kt:96)
	at com.dprint.services.editorservice.v5.EditorServiceV5.initialiseEditorService(EditorServiceV5.kt:29)
	at com.dprint.services.editorservice.EditorServiceManager.initialiseFreshEditorService(EditorServiceManager.kt:231)
	at com.dprint.services.editorservice.EditorServiceManager.restartEditorService$lambda$5(EditorServiceManager.kt:247)
	at com.dprint.services.editorservice.EditorServiceTaskQueue$createTaskWithTimeout$task$1.run$lambda$0(EditorServiceTaskQueue.kt:64)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 14 column 6 path $.typescript.exportDeclaration.forceMultiLine
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1754)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:588)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:498)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:875)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:820)
	at com.google.gson.internal.Streams.parse(Streams.java:46)
	... 18 more
```

After this, everything appears to work fine, but it's pretty annoying to have those errors on each project open.

Let me know if you need any other information from me.

MBP3 on MacOS 15.0, WebStorm 2024.3

**Comment by ryan-rushton** [comment]
It seems like the config file has some kind of json structure that googles `gson` library which I use to parse it doesn't like. @VVVHawk can you post your config file for me so I can check the syntax and see what is happening? I might just need to use a different tool to parse the json.

**Comment by VVVHawk** [comment]
Hey Ryan. The config is shared between our services, so most of the time the service-specific config is as follows:
```
{
  "includes": ["**/*.{js,jsx,ts,tsx,json}"],
  "extends": ["./node_modules/@common-config/config/dprint.json"]
}
```

The common config is
```
{
    "lineWidth": 180,
    "indentWidth": 4,
    "typescript": {
      "quoteStyle": "preferSingle",

      "module.sortImportDeclarations": "maintain",
      "module.sortExportDeclarations": "maintain",

      "importDeclaration.forceMultiLine": "whenMultiple",
      "exportDeclaration.forceMultiLine": "whenMultiple"
    },
    "json": {
      "indentWidth": 2,
      "trailingCommas": "never"
    },
    "excludes": [
      "**/build",
      "**/*-lock.json",
      "**/node_modules",
      "./integration-tests/src/shared/**",
      "./integration-tests/service-contracts/**"
    ],
    "plugins": [
      "https://plugins.dprint.dev/json-0.19.3.wasm",
      "https://plugins.dprint.dev/typescript-0.91.1.wasm"
    ]
}
```

**Comment by ryan-rushton** [comment]
Thanks, it seems like the google json library I was using to validate the json was well formed was getting tripped up on `"exportDeclaration.forceMultiLine": "whenMultiple"` which is odd. 

I've published a release which removes that validation, so it should be available in the next few days or you can manually install the 0.8.0 on the releases page here

**Comment by VVVHawk** [comment]
Tried it out, it works perfect now, thank you for the fast reaction!!

Closing the issue.
